### ISSUE TITLE
使用demo中得block方式，怎么消除进入主界面时有一段黑屏的问题

### ISSUE THREAD

**Issue by xiaolouxinyue** [iTofu/LCNewFeature#3]
RT，注释掉代码中得动画部分，感觉效果有点生硬。请教如何更优雅的进入主界面？

**Comment by iTofu** [comment]
在`LCNewFeatureVC.m` 的130行处，`-(void)setupMainView;` 方法里面添加一句：

``` objc
self.view.backgroundColor = [UIColor whiteColor];
```

试试。

**Comment by xiaolouxinyue** [comment]
不行，期待修正

**Comment by iTofu** [comment]
你的 application.keyWindow 的 backgroundColor 设为 whiteColor 应该就可以
