### ISSUE TITLE
iPhone6 + 的放大模式没有做判断

### ISSUE THREAD

**Issue by Yak0xff** [iTofu/LCNewFeature#4]
iPhone6 + 的放大模式没有做判断，导致使用了640 \* 960 的图。

**Comment by iTofu** [comment]
你好！请问 iPhone 6 + 指的是 iPhone 6 Plus吗？放大模式指的是？

**Comment by ghost** [comment]
我猜测他没有做适配。。。

**Comment by iTofu** [comment]
![simulator screen shot 2015 11 10 3 41 42](https://cloud.githubusercontent.com/assets/10044430/11056914/9f036734-87c1-11e5-856d-911344ad1a57.png)

**Comment by iTofu** [comment]
![simulator screen shot 2015 11 10 3 43 22](https://cloud.githubusercontent.com/assets/10044430/11056944/d1de0b0a-87c1-11e5-95e7-625376cd5266.png)

**Comment by iTofu** [comment]
iPhone 6 / 6 plus 都是可以的哦！

@RobinChao 
你说的 iPhone 6 放大模式是不是在 iPhone 6 上整个 App 的界面元素都放大了？
这种情况是非正常情况，原因是你没有给对 iPhone 6 的启动图，尺寸不对。
你可以尝试检查下启动图的尺寸，iPhone 6 的尺寸应该是 750 x 1334。

**Comment by Yak0xff** [comment]
测试过了，每个设备型号的尺寸都配置了，但是在方法模式下是取不到的。
iPhone6 puls  放大模式分辨率：1242, 2208
iPhone6 放大模式分辨率：1125, 2001

根据你的判断，拿不到对应的大尺寸图片。

**Comment by iTofu** [comment]
@RobinChao 
嗯，谢谢提醒！已修复该问题！
另经反复测试，放大模式下，iPhone 6 分辨率是 640 x 1136，iPhone 6 p 分辨率是 1125 x 2001 哦！

**Comment by Yak0xff** [comment]
3Q
