### ISSUE TITLE
适配iPad

### ISSUE THREAD

**Issue by Humein** [iTofu/LCNewFeature#6]
如果我想适配iPad，我新特性图片的iPad图片怎么命名呀

**Comment by Humein** [comment]
CGSizeEqualToSize(CGSizeMake(1125, 2001) 这个是哪个设备的分辨率呀

**Comment by Humein** [comment]
#define IPAD ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? (CGSizeEqualToSize(CGSizeMake(2732, 2048), [[UIScreen mainScreen] currentMode].size) || CGSizeEqualToSize(CGSizeMake(1024, 768), [[UIScreen mainScreen] currentMode].size)) : NO)

我用这个判断 当前设备是否是iPad 好像不对，不会走这里

**Comment by iTofu** [comment]
有种放大模式，分辨率不同。
iPad 未适配，你可以读下源码拓展下！

**Comment by Humein** [comment]
嗯 加上啦

**Comment by iTofu** [comment]
有时间的话可以 pull request 过来！

发自我的 iPhone

**Comment by Humein** [comment]
不会用 pull 呀 －－

**Comment by iTofu** [comment]
额，尴尬了哈哈。没事后面我抽空自己加吧。

发自我的 iPhone

**Comment by Humein** [comment]
嗯 谢谢啦0 0
